DROP TABLE USERS;
DROP SEQUENCE USER_SEQUENCE;


CREATE TABLE USERS 
(
ID 			SERIAL PRIMARY KEY,
USERNAME	VARCHAR(64),
PASSWORD	VARCHAR(128),
NAME		VARCHAR(64),
SURNAME		VARCHAR(64),
BIRTH_DATE	DATE
);

CREATE SEQUENCE USER_sequence
    INCREMENT 1
    START 1
    MINVALUE 1
;

ALTER TABLE ONLY users ALTER COLUMN id SET DEFAULT nextval('USER_sequence'::regclass);
ALTER TABLE users ADD CONSTRAINT users_uk UNIQUE (USERNAME);


INSERT INTO USERS (USERNAME, PASSWORD, NAME, SURNAME, BIRTH_DATE) VALUES ('Abc123', 'qwerty87', 'Andrea', 'Rossi', '1987-03-12');
INSERT INTO USERS (USERNAME, PASSWORD, NAME, SURNAME, BIRTH_DATE) VALUES ('Asd456', 'srgwerg', 'Mario', 'Verdi', '1985-04-13');
INSERT INTO USERS (USERNAME, PASSWORD, NAME, SURNAME, BIRTH_DATE) VALUES ('U04567', 'rtrrta', 'Federico', 'Massini', '1990-01-02');
INSERT INTO USERS (USERNAME, PASSWORD, NAME, SURNAME, BIRTH_DATE) VALUES ('BR23Wer', 'qwefarrr', 'Giorgia', 'Getti', '1970-11-21');
INSERT INTO USERS (USERNAME, PASSWORD, NAME, SURNAME, BIRTH_DATE) VALUES ('USER_TEST', 'qerv87rfy', 'Susanna', 'Soldini', '1981-03-15');
