CREATE TABLE USERS 
(
ID 			SERIAL PRIMARY KEY,
USERNAME	VARCHAR(64),
PASSWORD	VARCHAR(128),
NAME		VARCHAR(64),
SURNAME		VARCHAR(64),
BIRTH_DATE	DATE
);

CREATE SEQUENCE USER_sequence
    INCREMENT 1
    START 1
    MINVALUE 1
;

ALTER TABLE ONLY users ALTER COLUMN id SET DEFAULT nextval('USER_sequence'::regclass);
ALTER TABLE users ADD CONSTRAINT users_uk UNIQUE (USERNAME);